allow_k8s_contexts('polar')
update_settings(max_parallel_updates=1)

include('../../../config-service/Tiltfile')
include('../../../edge-service/Tiltfile')
include('../../../dispatcher-service/Tiltfile')
include('../../../order-service/Tiltfile')
include('../../../catalog-service/Tiltfile')
