CREATE TABLE IF NOT EXISTS bookOld (
    id BIGSERIAL PRIMARY KEY,
    isbn VARCHAR(255) UNIQUE NOT NULL,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    created_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version INTEGER NOT NULL DEFAULT 0
);

INSERT INTO bookOld (isbn, title, author, price, created_date, last_modified_date, version)
SELECT '1234567890', 'Polar Journey', 'Iorek Polarson', 12.90, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0
WHERE NOT EXISTS (SELECT 1 FROM bookOld WHERE isbn = '1234567890');
