apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "9002"
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: pxloc97/order-service:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"]
          ports:
            - containerPort: 9002
          env:
            - name: BPL_JAVA_NMT_ENABLED
              value: "false"
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/workspace/BOOT-INF/lib/opentelemetry-javaagent-1.33.3.jar"
            - name: OTEL_SERVICE_NAME
              value: "order-service"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://tempo:4317"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: POLAR_CATALOG_SERVICE_URL
              value: "http://catalog-service"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-service"
            - name: SPRING_R2DBC_URL
              value: "r2dbc:postgresql://polar-postgres/polardb_order"
            - name: SPRING_FLYWAY_URL
              value: "jdbc:postgresql://polar-postgres/polardb_order"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "polar-kafka:19092"
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "http://polar-keycloak/realms/PolarBookshop"
          volumeMounts:
            - name: order-service-volume
              mountPath: /workspace/config
            - name: order-service-volume-secret
              mountPath: /workspace/secrets/order-service
              readOnly: true
      volumes:
        - name: order-service-volume
          configMap:
            name: order-service
        - name: order-service-volume-secret
          secret:
            secretName: order-service
