apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service
  labels:
    app: edge-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: edge-service
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "9000"
      labels:
        app: edge-service
    spec:
      containers:
        - name: edge-service
          image: pxloc97/edge-service:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"]
          ports:
            - containerPort: 9000
          env:
            - name: BPL_JAVA_NMT_ENABLED
              value: "false"
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/workspace/BOOT-INF/lib/opentelemetry-javaagent-1.33.3.jar"
            - name: OTEL_SERVICE_NAME
              value: "edge-service"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://tempo:4317"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-service"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "polar-kafka:19092"
            - name: CATALOG_SERVICE_URL
              value: "http://catalog-service"
            - name: ORDER_SERVICE_URL
              value: "http://order-service:9002"
            - name: SPA_URL
              value: "http://polar-ui"
            - name: SPRING_REDIS_HOST
              value: "polar-redis"
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI
              value: "http://polar-keycloak/realms/PolarBookshop"
          volumeMounts:
            - name: edge-service-volume
              mountPath: /workspace/config
            - name: edge-service-volume-secret
              mountPath: /workspace/secrets/edge-service
              readOnly: true
      volumes:
        - name: edge-service-volume
          configMap:
            name: edge-service
        - name: edge-service-volume-secret
          secret:
            secretName: edge-service
