server:
  port: 9002
  shutdown: graceful
  netty:
    connection-timeout: 2s
spring:
  application:
    name: order-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888
      request-connect-timeout: 2000
      request-read-timeout: 5000
      fail-fast: true
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/polardb_order
    username: user
    password: password
    pool:
      max-size: 10
      initial-size: 2
      max-create-connection-time: 2s
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5433/polardb_order
