services:
  config-service:
    depends_on:
      - fluent-bit
      - tempo
      - polar-kafka
    image: "pxloc97/config-service:0.0.1-SNAPSHOT"
    container_name: "config-service"
    ports:
      - 8888:8888
      - 9888:9888
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:/workspace/config
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=9888
      - BPL_JAVA_NMT_ENABLED=false
      - BPL_JVM_THREAD_COUNT=50
      - JAVA_TOOL_OPTIONS=-javaagent:/workspace/BOOT-INF/lib/opentelemetry-javaagent-1.33.3.jar
      - OTEL_SERVICE_NAME=config-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4317
      - OTEL_METRICS_EXPORTER=none
      - ENCRYPT_KEY=sharedkey
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=polar-kafka:19092
    volumes:
      - ../../config:/workspace/config:ro
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 127.0.0.1:24224
        tag: "config-service"
    networks:
      - polar-network

  polar-postgres-catalog:
    image: "postgres:13.4"
    container_name: "polar-postgres-catalog"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=polardb_catalog
    networks:
      - polar-network

  polar-postgres-order:
    image: "postgres:13.4"
    container_name: "polar-postgres-order"
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=polardb_order
    networks:
      - polar-network

  polar-redis:
    image: "redis:6.2"
    container_name: "polar-redis"
    ports:
      - 6379:6379
    networks:
      - polar-network

  polar-kafka:
    image: apache/kafka:4.2.0
    hostname: polar-kafka
    container_name: polar-kafka
    user: "0:0"
    ports:
      - 9092:9092
    volumes:
      - kafka_data:/var/lib/kafka/data
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@polar-kafka:29093
      - KAFKA_LISTENERS=CONTROLLER://:29093,PLAINTEXT_HOST://:9092,PLAINTEXT://:19092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT_HOST://localhost:9092,PLAINTEXT://polar-kafka:19092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR=1
      - KAFKA_LOG_DIRS=/var/lib/kafka/data
      - CLUSTER_ID=4L6g3nShT-eMCtK--X86sw
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    networks:
      - polar-network

  polar-keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: polar-keycloak
    command: ["start-dev", "--http-port=8080", "--import-realm"]
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=user
      - KC_BOOTSTRAP_ADMIN_PASSWORD=password
      - KC_HOSTNAME_STRICT=false
    volumes:
      - ./keycloak/realm-config.json:/opt/keycloak/data/import/realm.json
    ports:
      - 8080:8080
    networks:
      - polar-network

  grafana:
    image: grafana/grafana:10.4.7
    container_name: grafana
    depends_on:
      - loki
      - prometheus
      - tempo
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: user
      GF_SECURITY_ADMIN_PASSWORD: password
    volumes:
      - ./platform/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./platform/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./platform/grafana/grafana.ini:/etc/grafana/grafana.ini
    networks:
      - polar-network

  loki:
    image: grafana/loki:2.9.8
    container_name: loki
    depends_on:
      - fluent-bit
    ports:
      - "3100:3100"
    networks:
      - polar-network

  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:main
    container_name: fluent-bit
    ports:
      - "24224:24224"
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - ./platform/fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    networks:
      - polar-network

  prometheus:
    image: quay.io/prometheus/prometheus:v2.52.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./platform/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - polar-network

  tempo:
    image: grafana/tempo:2.5.0
    container_name: tempo
    command: -config.file=/etc/tempo-config.yml
    ports:
      - "3110:3100"
      - "4317:4317"
    volumes:
      - ./platform/tempo/tempo.yml:/etc/tempo-config.yml
    networks:
      - polar-network

volumes:
  kafka_data:
    driver: local

networks:
  polar-network:
    name: polar-network
