services:
  polar-ui:
    image: ghcr.io/polarbookshop/polar-ui:v1
    container_name: polar-ui
    ports:
      - 9004:9004
    environment:
      - PORT=9004
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 127.0.0.1:24224
        tag: "polar-ui"
    networks:
      - polar-network

networks:
  polar-network:
    name: polar-network
