apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  labels:
    app: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "8888"
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service
          image: pxloc97/config-service:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 8888
          env:
            - name: BPL_JAVA_NMT_ENABLED
              value: "false"
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/workspace/BOOT-INF/lib/opentelemetry-javaagent-1.33.3.jar"
            - name: OTEL_SERVICE_NAME
              value: "config-service"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://tempo:4317"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
          volumeMounts:
            - name: config-service-volume
              mountPath: /workspace/config
            - name: config-service-volume-secret
              mountPath: /workspace/secrets/config-service
              readOnly: true
      volumes:
        - name: config-service-volume
          configMap:
            name: config-service
        - name: config-service-volume-secret
          secret:
            secretName: config-service
