apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  labels:
    app: inventory-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "9003"
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: pxloc97/inventory-service:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"]
          ports:
            - containerPort: 9003
          env:
            - name: BPL_JAVA_NMT_ENABLED
              value: "false"
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/workspace/BOOT-INF/lib/opentelemetry-javaagent-1.33.3.jar"
            - name: OTEL_SERVICE_NAME
              value: "inventory-service"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://tempo:4317"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-service"
            - name: SPRING_R2DBC_URL
              value: "r2dbc:postgresql://polar-postgres-inventory/polardb_inventory"
            - name: SPRING_FLYWAY_URL
              value: "jdbc:postgresql://polar-postgres-inventory/polardb_inventory"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "polar-kafka:19092"
          volumeMounts:
            - name: inventory-service-volume
              mountPath: /workspace/config
            - name: inventory-service-volume-secret
              mountPath: /workspace/secrets/inventory-service
              readOnly: true
      volumes:
        - name: inventory-service-volume
          configMap:
            name: inventory-service
        - name: inventory-service-volume-secret
          secret:
            secretName: inventory-service

