apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
  labels:
    app: catalog-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: "9001"
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: pxloc97/catalog-service:0.0.1-SNAPSHOT
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9001
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9001
            initialDelaySeconds: 5
            periodSeconds: 15
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"]
          ports:
            - containerPort: 9001
          env:
            - name: BPL_JAVA_NMT_ENABLED
              value: "false"
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/workspace/BOOT-INF/lib/opentelemetry-javaagent-1.33.3.jar"
            - name: OTEL_SERVICE_NAME
              value: "catalog-service"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://tempo:4317"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://polar-postgres:5432/polardb_catalog"
            - name: SPRING_DATASOURCE_USERNAME
              value: "user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "password"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-service"
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "http://polar-keycloak/realms/PolarBookshop"
          volumeMounts:
            - name: catalog-service-volume
              mountPath: /workspace/config
            - name: catalog-service-volume-secret
              mountPath: /workspace/secrets/catalog-service
              readOnly: true
      volumes:
        - name: catalog-service-volume
          configMap:
            name: catalog-service
        - name: catalog-service-volume-secret
          secret:
            secretName: catalog-service
