server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: config-service
  security:
    user:
      name: user
      password: password
  logging:
    level:
      org.springframework.security: DEBUG
  cloud:
    config:
      server:
        git:
          uri: https://github.com/prophet509/spring-native-bookstore.git
          default-label: main
          search-paths: config
          timeout: 5
          clone-on-start: true
          force-pull: true
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    connection-timeout: 2s

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
