name: CD Pipeline
on:
  push:
    branches: [main]

jobs:
  config-service-build:
    uses: ./.github/workflows/ci-config-pipeline.yml

  catalog-service-build:
    uses: ./.github/workflows/ci-catalog-pipeline.yml

